TRUTH = (
    "Have you ghosted someone?" "Have you ever walked in on your parents doing 'it'?",
    "Who was the last person you liked the most? Why?",
    "Have you ever been suspended from school?",
    "If you had to choose between going naked or having your thoughts appear in thought bubbles above your head for everyone to read, which would you choose?",
    "What’s the one thing you’re afraid to lose?",
    "Do you like someone as of the moment?",
    "One thing about your best friend you are jealous of?",
    "Would you cheat on your boyfriend for a rich guy?",
    "What is your biggest turn on?",
    "When’s the last time you lied to your parents and why?",
    "Describe your ideal partner.",
    "What’s the scariest thing you’ve ever done?",
    "Have you ever picked your nose and eaten it?",
    "When’s the last time you lied to your parents and why?",
    "Have you ever lied about your age to participate in a contest?",
    "Have you ever been caught checking someone out?",
)

DARE = (
    "Show the most embarrassing photo on your phone"
    "Show the last five people you texted and what the messages said",
    "Let the rest of the group DM someone from your Instagram account",
    "Eat a raw piece of garlic",
    "Do 100 squats",
    "Keep three ice cubes in your mouth until they melt",
    "Say something dirty to the person on your leftYou've got company!",
    "Give a foot massage to the person on your right",
    "Put 10 different available liquids into a cup and drink it",
    "*Yell out the first word that comes to your mind",
    "Give a lap dance to someone of your choice",
    "Remove four items of clothing",
    "Like the first 15 posts on your Facebook newsfeed",
    "Eat a spoonful of mustard",
    "Keep your eyes closed until it's your go again",
    "Send a sext to the last person in your phonebook",
    "Show off your orgasm face",
    "Seductively eat a banana",
    "Empty out your wallet/purse and show everyone what's inside",
    "Do your best sexy crawl",
    "Pretend to be the person to your right for 10 minutes",
    "Eat a snack without using your hands",
    "Say two honest things about everyone else in the group",
    "Twerk for a minute",
    "Try and make the group laugh as quickly as possible",
    "Try to put your whole fist in your mouth",
    "Tell everyone an embarrassing story about yourself",
    "Try to lick your elbow",
    "Post the oldest selfie on your phone on Instagram Stories",
    "Tell the saddest story you know",
    "Howl like a wolf for two minutes",
    "Dance without music for two minutes",
    "Pole dance with an imaginary pole",
    "Let someone else tickle you and try not to laugh",
    "Put as many snacks into your mouth at once as you can",
    "Send your most recent selfie.",
    "Send your ugliest selfie.",
    "Send a screenshot of your facebook search history",
    "Send a screenshot of your gallery.",
    "Send a screenshot of your messenger inbox",
    "Tell something very intimate.",
    "Send a screenshot of your twitter inbox",
    "Send a screenshot of your homescreen.",
    "Send a cover of your favorite song. 🎤",
    "Do a lyric prank on someone and send proof.",
    "Confess to your current crush. ❤️",
    "Declare who is your true love.",
    "Send a screenshot of your gallery.",
    "Set your crush’s picture as your dp.",
    "Suggest me more dares.",
)


SIGMA = (
    "https://te.legra.ph/file/4b69fbe424844911b8918.mp4",
    "https://te.legra.ph/file/cdb29d414660966a13c1d.mp4",
    "https://te.legra.ph/file/3692afc4a4c220cddd143.mp4",
    "https://te.legra.ph/file/9bec36decc0fa670b0972.mp4",
    "https://te.legra.ph/file/121f5914ec63a093833d4.mp4",
    "https://te.legra.ph/file/6da80542da78694e72772.mp4",
    "https://te.legra.ph/file/7612481a412ba8d6526f9.mp4",
    "https://te.legra.ph/file/c6fd080571a3184cf70fd.mp4",
    "https://te.legra.ph/file/d42c92ba73e4d6597cdaf.mp4",
    "https://te.legra.ph/file/26cf83b7e0c4919a7387f.mp4",
    "https://te.legra.ph/file/966efafa8444612ce17eb.mp4",
    "https://te.legra.ph/file/67d5b7bf76568da737bb3.mp4",
    "https://te.legra.ph/file/8bd84143da145f22efe7e.mp4",
    "https://te.legra.ph/file/5ef3b05e62a3d79bc134c.mp4",
    "https://te.legra.ph/file/9059707b626f16512902c.mp4",
    "https://te.legra.ph/file/eb8fd689e5bf148a3bccd.mp4",
    "https://te.legra.ph/file/7ae9f34f7bab75c62721a.mp4",
    "https://te.legra.ph/file/74c869332615283cbfcec.mp4",
    "https://te.legra.ph/file/18080231bf03cad0e36fb.mp4",
    "https://te.legra.ph/file/36b067368cbf3a506c42a.mp4",
    "https://te.legra.ph/file/cd0319a58d40f3c4bc2d0.mp4",
    "https://te.legra.ph/file/08a830bbcdbd8666d1fd8.mp4",
    "https://te.legra.ph/file/3a455d09e381d736a162e.mp4",
    "https://te.legra.ph/file/74c869332615283cbfcec.mp4",
    "https://te.legra.ph/file/a8cde9a02b2562ddc99f5.mp4",
    "https://te.legra.ph/file/5cb619fdc491eb9a86134.mp4",
    "https://te.legra.ph/file/3ca0f0637f5431a422818.mp4",
    "https://te.legra.ph/file/1e38235febfe52cdd0490.mp4",
    "https://te.legra.ph/file/e27fd617cc4e52835cb76.mp4",
)
